site_name: The Seedlings Project

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
    - header.autohide
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/SeedlingLogo.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ImmaculateDivinity/SeedlingEducation
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    feedback:
      title: Was the content organized?
      ratings:
        - icon: material/emoticon-happy-outline
          name: It was A, ok!
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Yeah. Terrible.
          data: 0
          note: >-
            I'll do better, just you see..

nav:
  - Home: 'index.md'
  - Getting Started: getstarted.md


copyright: >
  Copyright &copy; 2022 SeedlingsEducation –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - search
